name: .NET

on:
  push:
    branches: [master, net5]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.205'
      - name: Bootstrap Cake
        run: ./build.sh --target=Bootstrap --exclusive
      - name: Build
        run: ./build.sh --target=Build --exclusive
      - name: Test
        run: ./build.sh --target=Test --exclusive
